name: Build (Windows, UE)

on:
  workflow_dispatch:
# (no push/PR triggers for now)  
#  push:
#    branches: [ main ]
#  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, windows, ue]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show environment
        shell: pwsh
        run: |
          Write-Host "UE_ROOT=$env:UE_ROOT"
          Write-Host "UE_PROJECT_REL=$env:UE_PROJECT_REL"
          Write-Host "VS=$env:VISUAL_STUDIO_VERSION"

      - name: Generate project files
        shell: pwsh
        run: |
          & "${env:UE_ROOT}\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.exe" -Mode=GenerateProjectFiles

      - name: Build Editor target
        shell: pwsh
        run: |
          & "${env:UE_ROOT}\Engine\Build\BatchFiles\Build.bat" -Target="UnrealEditor Win64 Development" -WaitMutex -NoHotReload

      - name: Package Plugin (optional)
        shell: pwsh
        run: |
          $plugin = (Get-ChildItem -Path .\Plugins\* -Directory | Select-Object -First 1).FullName
          & "${env:UE_ROOT}\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin `
            -Plugin="$plugin\${(Split-Path $plugin -Leaf)}.uplugin" `
            -Package="$(Resolve-Path .\_packaged\plugin)" `
            -TargetPlatforms=Win64

      - name: Upload packaged plugin
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: packaged-plugin
          path: _packaged/plugin
